baseURL = "https://itiquette.github.io/"
languageCode = "en-us"
canonifyURLs = true
# Add it only if you keep the theme in the `themes` directory.
# Remove it if you use the theme as a remote Hugo Module.
theme = "terminal"
pagination.pagerSize = 5

# Required for Chroma and the custom syntax highlighting.
[markup.highlight]
noClasses = false

[params]
# dir name of your main content (default is `content/posts`).
# the list of set content will show up on your index page (baseurl).
contentTypeName = "posts"

# if you set this to 0, only submenu trigger will be visible
showMenuItems = 6

# show selector to switch language
showLanguageSelector = true

# set theme to full screen width
fullWidthTheme = false

# center theme with default width
centerTheme = true

# if your resource directory contains an image called `cover.(jpg|png|webp)`,
# then the file will be used as a cover automatically.
# With this option you don't have to put the `cover` param in a front-matter.
autoCover = true

# set post to show the last updated
# If you use git, you can set `enableGitInfo` to `true` and then post will automatically get the last updated
showLastUpdated = false

# Provide a string as a prefix for the last update date. By default, it looks like this: 2020-xx-xx [Updated: 2020-xx-xx] :: Author
# updatedDatePrefix = "Updated"

# whether to show a page's estimated reading time
# readingTime = false # default

# whether to show a table of contents
# can be overridden in a page's front-matter
# Toc = false # default

# set title for the table of contents
# can be overridden in a page's front-matter
# TocTitle = "Table of Contents" # default

# Set date/time format for posts
# This will impact the date/time displayed on
# index.html, the posts list page, and on posts themselves
# This value can also be configured per-post on front matter
# If you have any issues with the timezone rendering differently
# than you expected, please ensure your timezone is correctly set
# on your server.
# This value can be customized according to Hugo documentation:
# https://gohugo.io/functions/time/format/
# Default value (no changes needed):
# dateFormat = "2006-01-02"
# Example format, with date, time, and timezone abbreviation:
# dateFormat = "2006-01-02 3:04:06 PM MST"


[params.twitter]
# set Twitter handles for Twitter cards
# see https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started#card-and-content-attribution
# do not include @
creator = ""
site = ""

[languages]
[languages.en]
languageName = "English"
title = "Itiquette"

[languages.en.params]
subtitle = "Ad Astra"
owner = ""
keywords = ""
copyright = ""
menuMore = "Show more"
readMore = "Read more"
readOtherPosts = "Read other posts"
newerPosts = "Newer posts"
olderPosts = "Older posts"
missingContentMessage = "Page not found..."
missingBackButtonLabel = "Home"
minuteReadingTime = "min read"
words = "words"

[languages.en.params.logo]
logoText = ">"
logoHomeLink = "/"

[languages.en.menu]
[[languages.en.menu.main]]
identifier = "about"
name = "About"
url = "/about"
weight = 70
[[languages.en.menu.main]]
identifier = "blog"
name = "Blog"
url = "/posts/"
weight = 15
[[languages.en.menu.main]]
identifier = "projects"
name = "Projects"
url = "/projects"
weight = 20
[[languages.en.menu.main]]
identifier = "translations"
name = "Translations"
url = "/translations"
weight = 30
[[languages.en.menu.main]]
identifier = "shortcuts"
name = "Keyboard shortcuts"
url = "/shortcuts"
weight = 40
[[languages.en.menu.main]]
identifier = "tools"
name = "Tools"
url = "/tools"
weight = 50
[[languages.en.menu.main]]
identifier = "links"
name = "Links"
url = "/links"
weight = 60


# Svenska språkkonfigurationen
[languages.sv]
languageName = "Svenska"
title = "Itiquette"
[languages.sv.params]
subtitle = "Ad Astra"
owner = ""
keywords = ""
copyright = ""
menuMore = "Visa mer"
readMore = "Visa mer"
readOtherPosts = "Läs andra inlägg"
newerPosts = "Nyare inlägg"
olderPosts = "Äldre inlägg"
missingContentMessage = "Sidan hittades inte..."
missingBackButtonLabel = "Hem"
minuteReadingTime = "läst i..."
words = "ord"
[languages.sv.params.logo]
logoText = ">"
logoHomeLink = "/"
[languages.sv.menu]
[[languages.sv.menu.main]]
identifier = "om"
name = "Om"
url = "/sv/om"
weight = 70
[[languages.sv.menu.main]]
identifier = "blog"
name = "Blogg"
url = "/sv/posts/"
weight = 15
[[languages.sv.menu.main]]
identifier = "projects"
name = "Projekt"
url = "/sv/projects"
weight = 20
[[languages.sv.menu.main]]
identifier = "translations"
name = "Översättningar"
url = "/sv/translations"
weight = 30
[[languages.sv.menu.main]]
identifier = "shortcuts"
name = "Tangentbordsgenvägar"
url = "/sv/shortcuts"
weight = 40
[[languages.sv.menu.main]]
identifier = "tools"
name = "Verktyg"
url = "/sv/tools"
weight = 50
[[languages.sv.menu.main]]
identifier = "links"
name = "Länkar"
url = "/sv/links"
weight = 60

[caches]
[caches.images]
dir = ':cacheDir/images'


[[module.mounts]]
source = 'assets'
target = 'static/images'